### ISSUE TITLE
`dot` support during the build phase

### ISSUE THREAD

**Issue by drusellers** [weibeld/heroku-buildpack-graphviz#8]
In order for me to use `dot` in the build phase (during my jekyll build for example. I need to maintain a list of ENV var's to keep up to date.

Example 

```
# Ensure dot is in our path at build time and runtime in Heroku
if [ -d "$(pwd)/heroku-buildpack-graphviz/usr/bin" ]; then

  BASE="$(pwd)/heroku-buildpack-graphviz"
  export LD_LIBRARY_PATH=${BASE}/usr/lib:${BASE}/usr/lib/x86_64-linux-gnu/:\$LD_LIBRARY_PATH

  PATH="$(pwd)/heroku-buildpack-graphviz/usr/bin:$PATH"
fi
```

Would this kind of a change be a welcome PR?

**Comment by weibeld** [comment]
I'm not sure what exactly you mean with "during the build phase". During the execution of this buildpack? Or during the execution of another buildpack if you use multiple buildpacks?

For case 1, I just edited the code so that `PATH` and `LD_LIBRARY_PATH` are set in the buildpack, and it is possible to run `dot` in the buildpack (see [here](https://github.com/weibeld/heroku-buildpack-graphviz/blob/f6f1001ad2dcf771a931a59bedba590b3789579a/bin/compile#L79)).

For case 2, I just tested it and it seems that all environment variables are reset to the defaults when a new buildpack is executed. That means, even if we set `PATH` and `LD_LIBRARY_PATH` in this buildpack, then when the subsequent buildpacks are executed, these variables are not set anymore.

**Comment by drusellers** [comment]
> Or during the execution of another buildpack if you use multiple buildpacks?

During the execution of my Jekyll build step in the Ruby build pack, specifically.

> For case 2 ...

Ah, ok. Whoomp. Whoomp. :) Thank you for the answer. :)
